name: rp_generated_dart
description: "rp_generated_dart"
version: 0.0.1

environment:
  sdk: ^3.10.4

dependencies:
  protobuf: ^6.0.0
  grpc: ^5.1.0

dev_dependencies:
  test: ^1.29.0
  build_runner: ^2.10.5